Test jednostkowy - Evens And Odds
macmich981/maciej-michalski-kodilla-java pull request #2
Opened 2019-08-10 13:37 UTC by macmich981

2019-08-10 16:37 UTC, mps4dev requested changes
Drpbne korekty
👎

2019-08-10 16:37 UTC, mps4dev commented on kodilla-testing/src/test/java/com/kodilla/testing/collection/CollectionTestSuite.java
> +        //When
Tu jako argument powinna byc pusta lista (Collections.emptyList())

2019-08-10 16:37 UTC, mps4dev commented on kodilla-testing/src/test/java/com/kodilla/testing/collection/CollectionTestSuite.java
> +        Assert.assertTrue(results.get(1) == 4);
assertEquals(result, Arrays.asList(10,4,78))

2019-08-11 09:07 UTC, macmich981 reviewed
Poprawione

2019-08-12 06:39 UTC, mps4dev approved these changes
:+1:

2019-08-12 08:54 UTC, merged