Test 24.3 - aspect pattern for OrderFacade class
macmich981/maciej-michalski-kodilla-java pull request #35
Opened 2020-01-23 14:58 UTC by macmich981

2020-01-23 16:06 UTC, mps4dev requested changes
Czy to dziala z tym object?

2020-01-23 16:06 UTC, mps4dev commented on kodila-patterns2/src/main/java/com/kodilla/patterns2/facade/api/WatcherForOrder.java
> +@Component
Taka klase lepiej nazwac OrderAspect

2020-01-23 16:06 UTC, mps4dev commented on kodila-patterns2/src/main/java/com/kodilla/patterns2/facade/api/WatcherForOrder.java
> +    private void logEvent(OrderDto order, Long userId, Object object) {
Co to za object jest?

2020-01-23 16:06 UTC, mps4dev commented on kodila-patterns2/src/main/java/com/kodilla/patterns2/facade/api/WatcherForOrder.java
> +                .stream().map(item -> item.getProductId().toString()).collect(Collectors.joining(", ")) + " for user ID: " + userId);
To do zmiennej lokalnej - brzydko wyglada takie cos w zwyklej metodzie log()

2020-01-24 14:53 UTC, macmich981 commented
> Czy to dziala z tym object?

Przed wysłaniem na gita, zrobiłem test, a jego wynik był zgodny z oczekiwaniami. Od razy po teście, zbudowałem projekt poleceniem gradlew clean build i również tutaj było ok (nawiasem mówiąc, kod oparłem na przykładach z submodułu). Testu nie wysłałem, bo po prostu nie był częścią zadania. Tak czy owak wprowadziłem Twoje poprawki i również tutaj test i build ok.

2020-01-24 17:44 UTC, mps4dev approved these changes
Niech ci będzie :)

2020-01-24 18:02 UTC, merged